### ISSUE TITLE
Working solution

### ISSUE THREAD

**Issue by michaelhitzker** [htl-perg-2019-20-5bhif/contact-list-exercise-michaelhitzker#1]
Dear Mr. Stropek!

I have implemented all requirements specified in the swagger.yaml.

**Comment by rstropek** [comment]
Two things that I noticed:

* Avoid putting multiple classes in one file.
* **Format code** before checking it in.

Otherwise, well done. The extra point is yours.

Greetings,
Rainer Stropek.
